package:
  name: libsimplerasters
  version: "0.8.0"

source:
  path: ..

build:
  number: 0
  script: 
    - cmake -B build -S {{SRC_DIR}} -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS:bool=off -DPACK_DEB:bool=off
    - cmake --build build --config Release
    - cmake --install build --prefix {{PREFIX}}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - cmake
    - ninja
    - libgdal
  run:
    - libgdal

test:
  requires:
    - bash 
  commands:
    - test -f "${PREFIX}/lib/libsimplerasters.so"   
    - test -f "${PREFIX}/include/simplerasters/simplerasters.h"

about:
  home: https://github.com/JanCaha/cpp-simplerasters
  license: MIT
  summary: "C++ Raster Data Access Library based on GDAL"

extra:
  recipe-maintainers:
    - JanCaha
  channels:
    - conda-forge
    - defaults
