package:
  name: libsimplerasters
  version: "0.8.0"

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - cmake
    - ninja
    - libgdal
  run:
    - libgdal

test:
  requires:
    - bash # [unix]
  commands:
    - test -f "${PREFIX}/lib/libsimplerasters.so" # [unix]
    - test -f "${PREFIX}/lib/libsimplerasters.a" # [unix]
    - test -f "${PREFIX}/lib/cmake/SimpleRasters/SimpleRastersConfig.cmake" # [unix]
    - test -f "${PREFIX}/include/SimpleRasters/simplerasters.h" # [unix]

about:
  home: https://github.com/JanCaha/cpp-simplerasters
  license: MIT
  summary: "C++ Raster Data Access Library based on GDAL"

extra:
  recipe-maintainers:
    - JanCaha
  channels:
    - conda-forge
    - defaults
