name: Build on Win

on: 
    push:
        paths: ".github/workflows/build_windows.yaml"

jobs:

  Build-on-Win:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: install deps
        run: |
          C:/vcpkg/vcpkg install gdal gtest
          C:/vcpkg/vcpkg integrate install
          dir "C:/vcpkg/installed/x64-windows/bin"
        
      - name: Configure CMake
        run: |
          cmake -B build . -GNinja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreaded `
            -DCMAKE_TOOLCHAIN_FILE:PATH="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" 

      - name: Build
        run: cmake --build build --target all
      
      - name: Print
        run: |
            cd build
            dir  