name: Build on Win

on: 
    push:
        paths: ".github/workflows/build_windows.yaml"

jobs:

  Build-on-Win:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: install deps
        run: |
          C:/vcpkg/vcpkg install gdal gtest
          C:/vcpkg/vcpkg integrate install
          dir "C:/vcpkg/installed/x64-windows/bin"
        
      - name: isntall ninja
        run: |
            choco install ninja

      - name: set compiler environment
        shell: cmd
        run: |
            CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x86
    
      - name: Configure CMake
        run: |
          cmake -B build . -GNinja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreaded `
            -DCMAKE_TOOLCHAIN_FILE:PATH="C:\temp\vcpkg-llvm-$env:LLVM_VERSION\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET:STRING=x64-windows-static

      - name: Build
        run: cmake --build build --target all