name: Tests for Library

on: 
    push:
        paths: ".github/workflows/build_windows.yaml"

jobs:

  Tests-library:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: install deps
        run: |
          C:/vcpkg/vcpkg install gdal gtest
          C:/vcpkg/vcpkg integrate install
          dir "C:/vcpkg/installed/x64-windows/bin"
        
      - name: isntall ninja
        run: |
            choco install ninja

      - name: set compiler environment
        shell: cmd
        run: |
            CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x86
    
      - name: Configure CMake
        run: |
          cmake -B build . -GNinja `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target all