name: Change conda package version

on: push

jobs:

  Update-conda-package-version:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set Env variable with project version
        run: |
            echo "VERSION=$(grep "project(" CMakeLists.txt | grep -E -o -e "[0-9\.]+")" >> $GITHUB_OUTPUT
          
      - name: Print project version
        run: |
            echo "Project version: $VERSION"

      - name: Update conda package version
        run: |
          sed -i '/version: /c\  version: \"'$VERSION'\"' conda/meta.yaml
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Change to conda package version
            file_pattern: 'conda/meta.yaml'

