name: Create DEB artifact and Release

on:
  push:
    branches:
      - "main"
    tags:        
      - '**'

jobs:

  Create-deb-file-library:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build

      - name: Install GDAL
        run: |
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: | 
           mkdir build
            cmake \
            -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS:bool=off \
            -DPACK_DEB:bool=on

      - name: Build
        run: | 
          cmake --build build --config Release --target all

      - name: Pack deb file
        run: |
          cmake --build build --config Release --target pack_deb
      
      - name: Move deb file
        run: |
          mv _packages/simplerasters_*.deb .
          
      - name: Upload DEB file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: simplerasters
          path: simplerasters_*.deb
      
      - name: Version
        id: version
        run: |
          echo "VERSION=$(grep "project(" CMakeLists.txt | grep -E -o -e "[0-9\.]+")" >> $GITHUB_OUTPUT

      - name: Push tag
        uses: anothrNick/github-tag-action@1.64.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          CUSTOM_TAG : "v${{steps.version.outputs.VERSION}}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: viewshed_*.deb