name: Tests for Library

on: [push, pull_request]

jobs:

  Tests-library:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build

      - name: Install latest CMake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'
          
      - name: Install GDAL
        run: sudo apt-get -y install gdal-bin libgdal-dev
      
      - name: Install GTest and GMock
        run: sudo apt-get install libgtest-dev libgmock-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Configure
        run: | 
           mkdir build
           cmake \
            -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS:bool=on 

      - name: Build
        run: | 
           cmake --build build --config Release --target all

      - name: Run tests
        run: |
          cd build/tests
          ctest -VV

      - name: Test install
        run: |
          rm -rf build
          cmake \
            -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS:bool=off \
            -DPACK_DEB:bool=on
          sudo cmake --build build --config Release --target install

      - name: Version and latest tag
        id: version
        run: |
          echo "VERSION=$(grep "project(" CMakeLists.txt | grep -E -o -e "[0-9\.]+")" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          echo "CURRENT_TAG=v$(grep "project(" CMakeLists.txt | grep -E -o -e "[0-9\.]+")" >> $GITHUB_OUTPUT

      - name: Print
        run: |
          echo $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          echo ${{steps.version.outputs.VERSION}}
          echo ${{steps.version.outputs.LATEST_TAG}}
          echo ${{steps.version.outputs.CURRENT_TAG}}
          echo ${{ github.ref_name }}
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $latest_tag

      - name: NOT SAME TAG
        if: steps.version.outputs.CURRENT_TAG != steps.version.outputs.LATEST_TAG
        run: echo "${{steps.version.outputs.CURRENT_TAG}} != ${{steps.version.outputs.LATEST_TAG}}"
      
      - name : SAME TAG
        if: steps.version.outputs.CURRENT_TAG == steps.version.outputs.LATEST_TAG
        run: echo "${{steps.version.outputs.CURRENT_TAG}} == ${{steps.version.outputs.LATEST_TAG}}"