name: Tests for Library

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  Tests-library:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build g++-14

      - name: Install latest CMake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'

      - name: Install GDAL
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Install GTest and GMock
        run: sudo apt-get install libgtest-dev libgmock-dev

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          cmake --workflow --preset workflow-debug-tests

      - name: Test install
        run: |
          sudo cmake --workflow --preset workflow-release-install
