name: Tests for Library

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  Tests-library-linux:
    runs-on: ubuntu-26.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build g++-14

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Install GDAL
        run: |
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Install GTest and GMock
        run: sudo apt-get install libgtest-dev libgmock-dev

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          cmake --workflow --preset workflow-debug-tests

      - name: Test install
        run: |
          sudo cmake --workflow --preset workflow-release-install

  Tests-library-linux-sanitizers:
    runs-on: ubuntu-26.04

    steps:
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build g++-14

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Install GDAL
        run: |
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Install GTest and GMock
        run: sudo apt-get install libgtest-dev libgmock-dev

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run tests with AddressSanitizer and UndefinedBehaviorSanitizer
        run: |
          cmake --workflow --preset workflow-debug-sanitizers

  Tests-library-macos:
    runs-on: macos-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Install GDAL
        run: |
          brew update
          brew install gdal

      - name: Install GTest and GMock
        run: brew install googletest

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          cmake --workflow --preset workflow-debug-tests

      - name: Test install
        run: |
          sudo cmake --workflow --preset workflow-release-install
