name: Tests for Library

on: [push, pull_request]

jobs:

  Tests-library:
  
    runs-on: [ubuntu-20.04, ubuntu-22.04]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build

      - name: Install latest CMake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release -c) main" | sudo tee /etc/apt/sources.list.d/kitware.list

      - name: Install GDAL
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev
      
      - name: Install GTest and GMock
        run: sudo apt-get install libgtest-dev libgmock-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure
        run: | 
           mkdir build
           cmake \
            -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS:bool=on \
            -D CMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: | 
           cmake --build build --config Release --target all

      - name: Run tests
        run: |
          cd build/tests
          ctest -VV

      - name: Test install
        run: |
          rm -rf build
          cmake \
            -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS:bool=off \
            -DPACK_DEB:bool=on \
            -D CMAKE_INSTALL_PREFIX=/usr
          
          sudo cmake --build build --config Release --target install